extraction:
  cpp:
    after_prepare: 
      - python report.py 2
  cobol:
    after_prepare: 
      - python report.py 2
  csharp:
    after_prepare: 
      - python report.py 2
  java:
    after_prepare: 
      - python report.py 2
  javascript:
    after_prepare: 
      - python report.py 2
  python:
    after_prepare: 
      - python report.py 2
